name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
          
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: github-lambda
          zip_file: bundle.zip
          
      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws bucket name
          aws_bucket: demo8008
          # directory to upload
          source_dir: ./
          # destination directory for upload
          destination_dir: /
        
 
